# Use an official Node.js runtime as a parent image
FROM node:20.13.1

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm ci

# Copy the rest of the application source code to the working directory
COPY . .

# Run the database seeding command
RUN npm run seed:dev

# Run the application
CMD ["npm", "run", "dev"]

# Expose the port that the app runs on
EXPOSE 4000