import { UpdateQuery } from 'mongoose';

import { UserRoles } from '@/common/constants/enums';
import { IUserDoc } from '@/common/types/users';
import { env } from '@/common/utils/envConfig';

export const devUsers = [
  {
    username: 'admin',
    firstName: 'Admin',
    lastName: 'User',
    password: '12345Aa!',
    email: 'admin_user@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.ADMIN,
    status: 'active',
    phone: '123-456-7890',
    currentAddress: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '200 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '67890',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
    TFAEnabled: true,
  },
  {
    username: 'rana_faizan1',
    firstName: 'Rana',
    lastName: 'Faizan',
    password: '12345Aa!',
    email: 'rana_faizan1@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.VISITOR,
    status: 'active',
    phone: '123-456-7891',
    currentAddress: {
      street: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '456 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67890',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'visitor_user2',
    firstName: 'Visitor',
    lastName: 'User2',
    password: '12345Aa!',
    email: 'visitor_user2@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.VISITOR,
    status: 'active',
    phone: '123-456-0000',
    currentAddress: {
      street: '124 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12346',
      country: 'India',
    },
    postalAddress: {
      street: '457 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67891',
      country: 'India',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'visitor_user3',
    firstName: 'Visitor',
    lastName: 'User3',
    password: '12345Aa!',
    email: 'visitor_user3@example.com',
    passwordUpdateRequested: false,
    role: 'UserRoles.VISITOR',
    status: 'active',
    phone: '123-456-7893',
    currentAddress: {
      street: '125 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12347',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '458 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67892',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'visitor_user4',
    firstName: 'Visitor',
    lastName: 'User4',
    password: '12345Aa!',
    email: 'visitor_user4@example.com',
    passwordUpdateRequested: false,
    role: 'UserRoles.VISITOR',
    status: 'active',
    phone: '123-456-7899',
    currentAddress: {
      street: '126 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12348',
      country: 'India',
    },
    postalAddress: {
      street: '459 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67893',
      country: 'India',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'teacher_user1',
    firstName: 'Teacher',
    lastName: 'User1',
    password: '12345Aa!',
    email: 'teacher_user1@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.TEACHER,
    status: 'active',
    phone: '123-456-7895',
    currentAddress: {
      street: '127 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12349',
      country: 'USA',
    },
    postalAddress: {
      street: '460 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67894',
      country: 'USA',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'teacher_user2',
    firstName: 'Teacher',
    lastName: 'User2',
    password: '12345Aa!',
    email: 'teacher_user2@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.TEACHER,
    status: 'active',
    phone: '123-456-7896',
    currentAddress: {
      street: '128 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12350',
      country: 'India',
    },
    postalAddress: {
      street: '461 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67895',
      country: 'India',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'teacher_user3',
    firstName: 'Teacher',
    lastName: 'User3',
    password: '12345Aa!',
    email: 'teacher_user3@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.TEACHER,
    status: 'active',
    phone: '123-456-7897',
    currentAddress: {
      street: '129 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12351',
      country: 'Australia',
    },
    postalAddress: {
      street: '462 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67896',
      country: 'Australia',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'teacher_user4',
    firstName: 'Teacher',
    lastName: 'User4',
    password: '12345Aa!',
    email: 'teacher_user4@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.TEACHER,
    status: 'active',
    phone: '123-456-7898',
    currentAddress: {
      street: '130 Main St',
      city: 'Anytown',
      state: 'CA',
      zip: '12352',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '462 Another St',
      city: 'Sometown',
      state: 'NY',
      zip: '67896',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user1',
    firstName: 'Student',
    lastName: 'User1',
    password: '12345Aa!',
    email: 'student_user1@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-1111',
    currentAddress: {
      street: '101 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90001',
      country: 'India',
    },
    postalAddress: {
      street: '102 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10001',
      country: 'India',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user2',
    firstName: 'Student',
    lastName: 'User2',
    password: '12345Aa!',
    email: 'student_user2@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-7892',
    currentAddress: {
      street: '103 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90002',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '104 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10002',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user3',
    firstName: 'Student',
    lastName: 'User3',
    password: '12345Aa!',
    email: 'student_user3@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-9087',
    currentAddress: {
      street: '105 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90003',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '106 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10003',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user4',
    firstName: 'Student',
    lastName: 'User4',
    password: '12345Aa!',
    email: 'student_user4@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-7894',
    currentAddress: {
      street: '107 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90004',
      country: 'USA',
    },
    postalAddress: {
      street: '108 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10004',
      country: 'USA',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user5',
    firstName: 'Student',
    lastName: 'User5',
    password: '12345Aa!',
    email: 'student_user5@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-5555',
    currentAddress: {
      street: '109 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90005',
      country: 'India',
    },
    postalAddress: {
      street: '110 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10005',
      country: 'India',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user6',
    firstName: 'Student',
    lastName: 'User6',
    password: '12345Aa!',
    email: 'student_user6@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-1234',
    currentAddress: {
      street: '111 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90006',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '112 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10006',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user7',
    firstName: 'Student',
    lastName: 'User7',
    password: '12345Aa!',
    email: 'student_user7@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-7777',
    currentAddress: {
      street: '113 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90007',
      country: 'Dubai',
    },
    postalAddress: {
      street: '114 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10007',
      country: 'Dubai',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
  {
    username: 'student_user8',
    firstName: 'Student',
    lastName: 'User8',
    password: '12345Aa!',
    email: 'student_user8@example.com',
    passwordUpdateRequested: false,
    role: UserRoles.STUDENT,
    status: 'active',
    phone: '123-456-3333',
    currentAddress: {
      street: '115 Student St',
      city: 'Learnville',
      state: 'CA',
      zip: '90008',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '116 Study Ave',
      city: 'Readtown',
      state: 'NY',
      zip: '10008',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
  },
];

const stagingUsers = [...devUsers];

const prodUsers = [
  {
    username: 'prod_admin',
    firstName: 'Admin',
    lastName: 'User',
    password: '12345Aa!',
    email: 'admin_user@prod.com',
    passwordUpdateRequested: false,
    role: UserRoles.ADMIN,
    status: 'active',
    phone: '123-456-7890',
    currentAddress: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    postalAddress: {
      street: '200 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '67890',
      country: 'Pakistan',
    },
    emailVerified: true,
    phoneVerified: true,
    emailVerificationOTP: '',
    phoneVerificationOTP: '',
    forgotPasswordOTP: null,
    TFAEnabled: true,
  },
];

let users: UpdateQuery<IUserDoc> = [];
switch (env.NODE_ENV) {
  case 'development':
    users = devUsers;
    break;
  case 'production':
    users = prodUsers;
    break;
  case 'staging':
    users = stagingUsers;
    break;
  default:
    users = devUsers;
}

export { users };
