export const siteInfos = [
  {
    siteName: 'Murazik, Keeling and Adams',
    siteDescription: 'Down-sized national secured line',
    contactEmail: 'Annalise_Feest97@gmail.com',
    contactPhone: '1-787-597-0832 x35181',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Collins and Sons',
    siteDescription: 'Multi-layered exuding portal',
    contactEmail: 'Rowland.Jerde@yahoo.com',
    contactPhone: '991-238-4545',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'DuBuque, Brakus and Pfannerstill',
    siteDescription: 'Devolved non-volatile database',
    contactEmail: 'Alanna_Braun@yahoo.com',
    contactPhone: '268-575-4407 x78747',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Rutherford - Parker',
    siteDescription: 'Re-engineered tangible hardware',
    contactEmail: 'Maci.Lemke@yahoo.com',
    contactPhone: '774.880.9850',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Howe - Nolan',
    siteDescription: 'Seamless needs-based budgetary management',
    contactEmail: 'Haskell1@hotmail.com',
    contactPhone: '833-965-0602',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Rodriguez - Schultz',
    siteDescription: 'Upgradable solution-oriented projection',
    contactEmail: 'Jewell.Graham92@gmail.com',
    contactPhone: '(441) 893-1814 x9243',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: "Conn, Satterfield and O'Kon",
    siteDescription: 'Synchronised responsive functionalities',
    contactEmail: 'Candice_Cremin67@hotmail.com',
    contactPhone: '(356) 761-3142 x77834',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Medhurst, Franecki and Walter',
    siteDescription: 'Streamlined local migration',
    contactEmail: 'Kacey.Koch@gmail.com',
    contactPhone: '1-481-856-1053',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Rippin, Waelchi and Pagac',
    siteDescription: 'Function-based systemic projection',
    contactEmail: 'Breana.Johnston@gmail.com',
    contactPhone: '907.582.3537 x5981',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Stiedemann - Spencer',
    siteDescription: 'Exclusive logistical emulation',
    contactEmail: 'Guy83@hotmail.com',
    contactPhone: '(457) 342-4763',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Pouros - Harris',
    siteDescription: 'Function-based transitional instruction set',
    contactEmail: 'Albin.Watsica23@hotmail.com',
    contactPhone: '932.483.5208',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Spencer and Sons',
    siteDescription: 'Devolved responsive secured line',
    contactEmail: 'Jayne85@gmail.com',
    contactPhone: '1-284-961-7532 x449',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: "Carroll, D'Amore and Botsford",
    siteDescription: 'Persistent 24 hour interface',
    contactEmail: 'Aniyah42@gmail.com',
    contactPhone: '514-934-9419',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Kassulke - Hammes',
    siteDescription: 'Operative radical emulation',
    contactEmail: 'Orland90@yahoo.com',
    contactPhone: '418-322-1859',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Nolan - Deckow',
    siteDescription: 'Mandatory leading edge matrix',
    contactEmail: 'Manuela42@yahoo.com',
    contactPhone: '930-939-1101',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Durgan - Feil',
    siteDescription: 'Mandatory national task-force',
    contactEmail: 'Efren_Lubowitz86@hotmail.com',
    contactPhone: '511-818-0038',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Will - Prosacco',
    siteDescription: 'Universal modular instruction set',
    contactEmail: 'Bettie_Hagenes45@gmail.com',
    contactPhone: '(311) 366-4575 x0761',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Goldner, Abbott and Kiehn',
    siteDescription: 'Networked intangible encryption',
    contactEmail: 'Liliane.Zulauf@yahoo.com',
    contactPhone: '982.387.0971 x72621',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Gerlach, Bartoletti and Lynch',
    siteDescription: 'User-centric bottom-line capability',
    contactEmail: 'Addison_Lueilwitz@hotmail.com',
    contactPhone: '520.776.2167 x127',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
  {
    siteName: 'Fadel, Johns and Goyette',
    siteDescription: 'Networked secondary forecast',
    contactEmail: 'Major.Purdy@yahoo.com',
    contactPhone: '1-506-351-6126 x69859',
    address: {
      street: '100 Admin St',
      city: 'Admin City',
      state: 'AC',
      zip: '12345',
      country: 'Pakistan',
    },
    socialLinks: {
      facebook: 'https://www.facebook.com',
      twitter: 'https://www.twitter.com',
      linkedin: 'https://www.linkedin.com',
      instagram: 'https://www.instagram.com',
    },
    logoUrl: 'http://placeimg.com/640/480',
  },
];
